### ISSUE TITLE
Mac: cannot paste

### ISSUE THREAD

**Issue by cliffordp** [sushantshekhar20/keep_electron#1]
macOS High Sierra version 10.13.3

Cannot Cmd+V or Cmd+Shift+V or right-click to paste into the Google Account Sign-In password field or anywhere within the app once signed in.

The right-click does bring up any action items; it's like it's fully ignored.

**Comment by sheksushant** [comment]
Its in my Features To Add pipeline (see readme.md).
I am not getting time to fix it due to other work commitments. But would update soon.
